### ISSUE TITLE
Battle Karten neu anorden auf dem Bildschirm (96)

### ISSUE THREAD

**Issue by DenisTh** [Icii/Cardgame#1]
Nach 3 Kampf Karten laufen die nächsten Karten aus dem Bildschirm raus.
Bitte Kampfkarte 4-6 neu Positionieren. Pyramiedenförmig, Karten insgesamt etwas Kleiner machen?

**Comment by Icii** [comment]
Es gibt jetzt für jedes Kartenpaar ein speziellen Slot.
