### ISSUE TITLE
Battle ausgewählte Karte sieht man noch von der seite. (95)

### ISSUE THREAD

**Issue by DenisTh** [Icii/Cardgame#2]
Die Karten die man selbst und der Gegner gewählt hat sieht man noch von der Seite. So drehen das man eigene Karte von vorne sieht und die generkarte von hinten.

**Comment by Icii** [comment]
Commit: https://github.com/Icii/Cardgame/commit/6eadfb42c463bb4c594c4445248c49ce2375361b
