### ISSUE TITLE
Eigenen Stack öffenkönnen (85)

### ISSUE THREAD

**Issue by DenisTh** [Icii/Cardgame#8]
Nach sehen welche Karten im Stack sind. 
-Karten groß auf dem Canvas anzeigen (verdeckung ist egal).
-Button zum schließen.

**Comment by Icii** [comment]
Wenn wir auf einen bereits ausgewählten Stack nochmal klicken, wird der Inhalt des Stacks angezeigt.
Zum schliessen müssen wir nur irgendwo in das Spiel klicken.
https://github.com/Icii/Cardgame/commit/42a26f8d4c68d2279f04d11ba1e67e315ba739d1
